### ISSUE TITLE
move os.system to os.subprocess

### ISSUE THREAD

**Issue by CodeCrafter912** [linuxmuster/linuxmuster-linuxclient7#15]
move all os.system calls to os.subprocess. os.system is deprecated, and it is not recommended using it anymore.

**Comment by kiarn** [comment]
Hello @CodeCrafter912 ,

Not `os.subprocess`, but [subprocess](https://docs.python.org/3/library/subprocess.html)
There's plentyresources in internet to describe why, e.g. https://stackoverflow.com/questions/44730935/advantages-of-subprocess-over-os-system :)

**Comment by CodeCrafter912** [comment]
HI @kiarn 

Yes, you are correct, I mistyped it :)
I also found some resources and especially the shell injection vulnerability of os.system makes it necessary to switch.

Unrelated: maybe should also tell Thomas to adapt linuxmuster base. Looks like he really loves os.system ;) 
https://github.com/linuxmuster/linuxmuster-prepare/blob/14c1ca15985b900936d8caf2ff475aa25521f046/sbin/linuxmuster-prepare#L529

**Comment by kiarn** [comment]
Oh, I didn't see it, I open an issue.

**Comment by CodeCrafter912** [comment]
I will use this opportunity to remove as many system calls as possible by using native apis.

**Comment by CodeCrafter912** [comment]
see: https://github.com/linuxmuster/linuxmuster-linuxclient7/issues/17
