### ISSUE TITLE
Create example hookscripts

### ISSUE THREAD

**Issue by dorianim** [linuxmuster/linuxmuster-linuxclient7#16]
Create some example hook scripts for common tasks and publish them in the wiki.
Scripts should be created for:
- [ ] Persistent profile storage on the server
- [ ] Setting wallpaper from server

More ideas are welcome :)

**Comment by dorianim** [comment]
This is an example on how to create static links of the following directorsy to the server home: Dokumente, Bilder, Musik, Videos, Downloads
```
# link dirs to server
for dir in Dokumente Musik Bilder Videos Downloads
do
  rmdir $HOME/$dir 2> /dev/null
  mkdir "$SERVERHOME/$dir" 2> /dev/null
  ln -sfn "$SERVERHOME/$dir" "$HOME/$dir"
done
```

**Comment by lawilfried** [comment]
My goal was a symbolic link on the desktop that leads directly to the user's home directory. At first I installed the gnome-extension "desktop-icons" with the browser and turned the extension on. Then I closed the browser. With a right click on the Desktop one get a window with settings. The second  point  offers the possibility to stop showing the home of linuxadmin on the desktop. After this there is a good place for the symbolic link in the upper left corner of the desktop.
And this is the "script" (it's only one line!) in the `/etc/linuxmusterLinuxclient7/onLogin.d`, called "`testhome.sh`":

```
#!/bin/bash
ln -sfn "$SERVERHOME"  "$HOME/Schreibtisch/§USER"

```

**Comment by lawilfried** [comment]
This script enables a user to save his own settings in his home directory on the server. In this case you can save settings for the Firefox application, e.g. bookmarks. For the first time it is necessary that there is no directory with previous settings and no symlink either. Please delete it before the script runs for the first time. The right place for the script is here: `/etc/linuxmusterLinuxclient7/onLogin.d `  
The content is based on the work of the developers of linuxmuster and Dominik Förderer. 

```
#!/bin/bash

# firefox profile on user share
if [ -d "$SERVERHOME/Einstellungen/firefox" ]; then            
    rm -rf "$HOME/.mozilla/firefox"                             
    ln -s "$SERVERHOME/Einstellungen/firefox" "$HOME/.mozilla/" 
else
    mkdir -p "$SERVERHOME/Einstellungen/firefox"               
    mv "$HOME/.mozilla/firefox" "$SERVERHOME/Einstellungen/"    
    ln -s "$SERVERHOME/Einstellungen/firefox" "$HOME/.mozilla/" 
fi
```
The script can be a template for other applications.

**Comment by dorianim** [comment]
This will be handled by "plugins" in the future. @lawilfried feel free to create pull requests to add you snippets as plugins :)

See the wiki over here: https://github.com/linuxmuster/linuxmuster-linuxclient7/wiki/About-plugins

Once there are more than 10 plugins, I may create a to to install them, something like `linuxmuster-linuxclient7 install-plugin conky`
