### ISSUE TITLE
Use Python API instead of system calls for apt

### ISSUE THREAD

**Issue by CodeCrafter912** [linuxmuster/linuxmuster-linuxclient7#17]
For apt update and upgrade it is possible to use native python code instead of a system call:
https://gist.github.com/yumminhuang/8b1502a49d8b20a6ae70

**Comment by CodeCrafter912** [comment]
Over here: https://github.com/linuxmuster/linuxmuster-linuxclient7/blob/4969e411fe80621d75eec27aed8d209b64da4056/usr/lib/python3/dist-packages/linuxmusterLinuxclient7/imageHelper.py#L69

**Comment by kiarn** [comment]
Another example : https://github.com/ajenti/ajenti/blob/master/plugins/packages/managers/apt_manager.py

**Comment by CodeCrafter912** [comment]
Thats cool!
Do you also have something for systemd?

**Comment by kiarn** [comment]
In `Ajenti` we are still using `subprocess` to manage `systemd` : https://github.com/ajenti/ajenti/blob/master/plugins/services/managers/systemd_manager.py

I just found this : https://github.com/systemd/python-systemd, but I didn't try it, maybe it worth having an eye on it.

**Comment by CodeCrafter912** [comment]
Yes, I found that two, but it does not seem.to be very well maintained.

**Comment by CodeCrafter912** [comment]
I decided not to do this using native python as I couldn't get it to work in a reasonable amount of time.
