### ISSUE TITLE
Hinweis im Wiki zur Überbleibsel alter Linuxclient

### ISSUE THREAD

**Issue by sedding** [linuxmuster/linuxmuster-linuxclient7#25]
Hej,
habe gerade festgestellt, dass nach der Migration noch eine Datei `/etc/profile.d/linuxmuster-proxy.sh` existiert, die von `apt purge linuxmuster-client-adsso` nicht weggeputzt wurde. 
Dadurch werden die proxy-Einstellungen, die von den custom scripts gesetzt werden, überschrieben.

M.E. sollte dazu ein Hinweis auf die Wiki-Seite zur Migration, dass die alte Datei noch händisch weggelöscht werden muss... Sonst fällt einem das irgendwann auf die Füße.

Grüße
Michael

**Comment by dorianim** [comment]
Hi, 
Das ist nich nötig, die Datei wird beim Setup weggelöscht.
Siehe hier:
https://github.com/linuxmuster/linuxmuster-linuxclient7/blob/3eb7d17ec0232d51ac194a30e45399f0bf908379/usr/lib/python3/dist-packages/linuxmusterLinuxclient7/constants.py#L27

VG, Dorian

**Comment by dorianim** [comment]
Does not seem to work in any case:
https://ask.linuxmuster.net/t/proxyeinstellung-funktioniert-nur-halb/8067
