### ISSUE TITLE
Dont use absolute path for binaries

### ISSUE THREAD

**Issue by dorianim** [linuxmuster/linuxmuster-linuxclient7#28]
Dont use an absolute path for binaries in subprocess calls!
They are not always in the same place.

See:
https://ask.linuxmuster.net/t/linuxclient-kein-login-moeglich/7930/53

**Comment by kiarn** [comment]
You can first verify the path with `which mount.cifs`. That's what I do for non-standards binary in `ajenti`.

Arnaud

**Comment by dorianim** [comment]
Could also use this:
https://docs.python.org/dev/library/shutil.html#shutil.which
