### ISSUE TITLE
Shares not shown when useLetter is 0

### ISSUE THREAD

**Issue by Hexxpert** [linuxmuster/linuxmuster-linuxclient7#31]
File: gpo.py
On GitHub line 226 creates brackets and colon even if useLetter is 0. Doesn't make sense.
On Linuxmuster-Installation from 2021-10-02 (no version info in file) it is improved to (starting on line 227):
    for drive in shareList:
        if drive["useLetter"] == "1":
            shareName = f"{drive['label']} ({drive['letter']}:)"  
        else:
            "{drive['label']}"
        shares.mountShare(drive["path"], shareName=shareName)
This leads to that these shares are no mounted anymore because the sharename is missing.
Correct way is:
    for drive in shareList:
        if drive["useLetter"] == "1":
            shareName = f"{drive['label']} ({drive['letter']}:)"  
        else:
            **shareName = f**"{drive['label']}"  
        shares.mountShare(drive["path"], shareName=shareName)
Works fine! => Please update in the next release.

**Comment by Hexxpert** [comment]
fixed half an hour later ... at least in the lmn7 repos!

**Comment by dorianim** [comment]
I fixed this yesterday:
ebc46a2869bdb0d320fa06a7ff4dbc9faf631b58
https://ask.linuxmuster.net/t/neue-pakete-fuer-lmn7/5237/193?u=dorian
