### ISSUE TITLE
Execution order of scripts in /etc/linuxmuster7-linuxclient

### ISSUE THREAD

**Issue by lemertens** [linuxmuster/linuxmuster-linuxclient7#48]
The example script's name (00_example.sh) implies that scripts are executed in alphabetical order. This is is not ensured as os.listdir does not ensure any order ( [as stated here](https://docs.python.org/3/library/os.html): " The list is in arbitrary order, ").
Example output of os.listdir ( Ubuntu 20.04)
```
>>> import os
>>> print (os.listdir('/tmp/test'))
['02_asd', '03_234', '01_a']
>>> 
```

I propose changing line 57 of hook.py from
`    for fileName in os.listdir(hookDir): `
to
`    for fileName in sorted(os.listdir(hookDir)):`

**Comment by dorianim** [comment]
Feel free to open a pull request :)
