### ISSUE TITLE
logoff.sh is never executed

### ISSUE THREAD

**Issue by hackbert** [linuxmuster/linuxmuster-linuxclient7#71]
As described in the wiki (see proxy configuration) there is a mechanism to run some scripts on boot, login etc.
These scripts are located on the server, mounted via sysvol and then executed as hooks on the client (see hooks.py)

On the Server, there are these scripts:
logoff.sh  logon.sh  sysstart.sh  sysstop.sh

In hooks.py there is logoff.sh missing:
remoteScriptNames = {
    Type.Boot: "sysstart.sh",
    Type.Login: "logon.sh",
    Type.SessionStarted: "sessionstart.sh",
    Type.Shutdown: "sysstop.sh"
}

We wanted to unset the Proxy settings on logoff. If we configure linuxclients as described in wiki, the Proxy settings are persistent. So we need to unset them somewhere for clients that should also work at home.

PS "sessionstart.sh" does not exist on the server (should be part of  sophomorix-samba package)

**Comment by dorianim** [comment]
As you can see here, the logoff script is on implemented:
https://github.com/linuxmuster/linuxmuster-linuxclient7/wiki/Hook-scripts

There does not seem to be an easy in Linux way to execute a script on logout in the user context. Therefore, this will not be implemented.

If you need to enable the proxy only in certain conditions ([which seems to be what you want to do](https://ask.linuxmuster.net/t/linuxclient-notebook-proxy/10177)), you need to add a condition in the logon script.
